# AMPS support uses this to test every release
FROM ubuntu
MAINTAINER 60East Technologies <support@crankuptheamps.com>
ADD http://devnull.crankuptheamps.com/releases/amps/AMPS-develop-Release-Linux.tar.gz /binaries/AMPS.tar
COPY amps-config.xml /
RUN ls -l /
RUN ls -l /binaries
RUN tar xvf /binaries/AMPS.tar --transform='s,AMPS[^/]*/,AMPS/,'
RUN ls -l /
 
 
# expose json tcp port
EXPOSE 9007
# expose admin port
EXPOSE 8085
 
CMD ["/AMPS/bin/ampServer","amps-config.xml"]
